### POST req to create patient
POST http://lb-5aca2aa0.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe with billing account",
  "email": "analytics_test@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}
###